/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "GPIO.h"
#include "NVIC_Interface.h"



int main(void)
{

	/* enable GPIOA CLK */
	*((volatile uint32_t*)(0x40023800 + 0x30)) |= 1; /* AHB1ENR*/

	PIN_CONFIG_T P5 =
	{
			.PORT= PORTA,
			.Mode= OUTPUT,
			.OTYPE= Output_push_pull0,
			.SPEED= LOW_Speed,
			.PIN= PIN5
	};


	GPIO_PinInit(&P5);

	GPIO_SetPinValue(PORTA, PIN5, ONE); /* LED ON */
	
	SCB_voidSetPriorityGroup(_2_BitsGroupPriority_2_SubPriority);  /* group=0,1,2,3 // sub = 0,1,2,3*/

	NVIC_SetPriority(EXTI0, 10); /* Lower priority */

	NVIC_SetPriority(EXTI1, 5); /* higher priority*/

	NVIC_EnableIRQ(EXTI0);

	NVIC_EnableIRQ(EXTI1);

	NVIC_SetPendingIRQ(EXTI0); /* set pending flag sw to generate EXTI0 interrupt */


	/* Global enabled by default*/


	/* Loop forever */
	for(;;);
}

void EXTI0_IRQHandler(void)
{
	NVIC_SetPendingIRQ(EXTI1); /* set pending flag sw to generate EXTI1 interrupt */
	while(1);
}
void EXTI1_IRQHandler(void)
{
	GPIO_SetPinValue(PORTA, PIN5, ZERO);
}
